algoritmo "Conversão de Temperatura"
// Função :   Converter grau Celsius(C) em Fahrenheit(F)
// Autor :   Thiago Souza
// Data : 06/05/2018

var  c,f: real

inicio

Escreval("**** CONVERSÃO DE TEMPERATURA ****")
Escreval("**** ESTE PROGRAMA CONVERTE TEMPERATURA CELSIUS(C) EM FAHRENHEIT(F) ****")
Escreval("Digite o valor da temperatura em Celsius(C)")
Leia(c)
f <- (9*c + 160)/5
Escreval(" A temperatura em Fahrenheit é:"," ",f,"F")

fimalgoritmo
